### ISSUE TITLE
image generation not working

### ISSUE THREAD

**Issue by hulluP** [Redth/ResizetizerNT#1]
Hi

I followed the blog and used the preview 8 and did not get any thing working. Can you let me know why that is the case?
the Git is:
https://github.com/hulluP/imageTest

thanks HP

**Comment by Redth** [comment]
@hulluP can you make that repo public?  I don't have access to see it.

**Comment by hulluP** [comment]
@Redth 
sorry that was rookie mistake, which I just fixed.
HP

**Comment by Redth** [comment]
Looks like you need to install the Resizetizer.NT nuget package into your iOS and android app projects.

**Comment by hulluP** [comment]
Thanks my fault for missing that part in the documentation.
Thanks for the great plugin.
