### ISSUE TITLE
Nuget installation does not include the "SharedImage" Build Action

### ISSUE THREAD

**Issue by wagesj45** [Redth/ResizetizerNT#11]
When installing the Nuget package, both *Stable 0.1.0* and *Preview 0.1.0-8*, the `SharedImage` build action is not included in the base Xamarin Forms project. It **is** included on the `*.Android`, `*.iOS`, and `*.UWP` projects.

![image](https://user-images.githubusercontent.com/2460850/82643897-f93bb300-9bd5-11ea-95ef-6e05d4a74154.png)

![image](https://user-images.githubusercontent.com/2460850/82643973-27b98e00-9bd6-11ea-9a11-458c85d2e493.png)

**Comment by Redth** [comment]
Did you restart Visual Studio after you installed the NuGet package?

**Comment by wagesj45** [comment]
Yes. Restarted Visual Studio, updated to latest version and started again, restarted Windows, restarted everything. It did not show up or include the build action when I tried installing again.

**Comment by Redth** [comment]
Very odd.  I can't really do much more about that, I've already defined the [AvailableItemName](https://github.com/Redth/ResizetizerNT/blob/master/Resizetizer.NT/Resizetizer.NT.targets#L5) for it, the IDE needs to do the rest.

You can of course still manually edit your .csproj and add your items:

```
<ItemGroup>
  <SharedImage Include="Icons\cog.svg" BaseSize="100,100" />
</ItemGroup>
```
