### ISSUE TITLE
Question: Can images be accessed within code?

### ISSUE THREAD

**Issue by JulesMoorhouse** [Redth/ResizetizerNT#14]
Can images be accessed within code rather than a xaml file?

I can see that the images are generated in the build folder, but I don't believe these will be accessible in code.

Obviously the Android Resource.designer.cs will just pick up images added to the Android project, likewise iOS are added to the bundle.

Edit: I mean in platform code, within say a custom renderer.

**Comment by Redth** [comment]
Sure, the images are just resources in their respective projects as you would normally include them.  There is nothing special or proprietary about how they are included on each platform, it's just that they are _automatically_ included for you.
