### ISSUE TITLE
Recreating images

### ISSUE THREAD

**Issue by K232** [Redth/ResizetizerNT#25]
Hi! 
Sorry I did not find it in the docs: Are the images created on every build, or does ResizetizerNT detect whether an existing SharedImage has been updated and then only recreated the updated ones? I have some hundreds images in my app and I guess recreating all images on every build will take some time....
Many thanks!

**Comment by Redth** [comment]
The task uses inputs and outputs according to msbuild best practices.  Basically the source images themselves as well as their metadata inside the project item groups are used as the 'inputs' and the task will only run if the outputs (the generated images) are older than any of the inputs.  So with no changes to inputs the task should not run at all on subsequent builds.

Even if the task _does_ run there is also some logic to skip over regenerating images which haven't changed as well.
