### ISSUE TITLE
Not working on Debug for Android

### ISSUE THREAD

**Issue by ThiagoAguirreLorscheiter** [Redth/ResizetizerNT#26]
First of all thanks for sharing this wonderful tool /code and saving us time from the boring work of resizing all images.

Basic INFO:
resizetizer version: 0.1
Android target SDK: 29

Everything was working fine until I had to format my PC and reinstall VS.

On iOS and Release for Android everything works normal, except in Debug mode for Android. I've tried to delete the bin and obj folders and clean up the solution.

The obj\Debug\100\resizetizer folder is created and all files are inside.

I tried to reinstall the NuGet packet, and nothing, same result.

No changes to the project settings were made(from when it was working, prior to the formatting), I tried to disable the "use shared runtime" and "use fast deployment", I left aapt2 also disabled, and tried to change the Dex Compiler but neither dx nor d8 work. Linking is disabled as well.

The building output looks normal:
1>------ Build started: Project: AppResources, Configuration: Debug Any CPU ------
1>AppResources -> E:\Jumpear\Projetos\Autoparts\SuperPerformance\Resources\AppResources\bin\Debug\netstandard2.0\AppResources.dll
2>------ Build started: Project: SuperPerformance.Images, Configuration: Debug Any CPU ------
2>SuperPerformance.Images -> E:\Jumpear\Projetos\Autoparts\SuperPerformance\Superedition\SuperPerformance.Images\bin\Debug\netstandard2.0\SuperPerformance.Images.dll
3>------ Build started: Project: CoreRx, Configuration: Debug Any CPU ------

Thanks again.
Thiago Aguirre Lorscheiter

**Comment by MagicAndre1981** [comment]
> resizetizer version: **0.1**
> Android target SDK: 29
> 
> Everything was working fine until I had to format my PC and **reinstall VS.**

You may run into #23 , so try [0.2.0-preview1](https://www.nuget.org/packages/Resizetizer.NT/0.2.0-preview1)

**Comment by ThiagoAguirreLorscheiter** [comment]
Thank you @MagicAndre1981 
Updating to 0.2.0-preview1 solved the issue.

Regards,
Thiago Aguirre Lorscheiter

**Comment by dais-set** [comment]
It would appear this issue is not fixed in 0.2.0-preview1 (using latest VS2019). Images work in iOS but in the Android project, while the .png are created in \obj\Debug\100\resizetizer, nothing gets to our Resources. Any ideas if this can be fixed? We had an idea we might use the plugin to simplify our redesign but we'd need both Android and iOS versions working,
I noticed you've had lots of those same bugs with the Android images not being generated, conflicts with notifications configuration, etc.

**Comment by MagicAndre1981** [comment]
@dais-set the data are not added to Asset/Resource folder, they are added to app directly

**Comment by dais-set** [comment]
I see, then how would I go about investigating why the icons are not working in the Android version?

**Comment by MagicAndre1981** [comment]
[watch the video](https://www.youtube.com/watch?v=O7a7HKiFypw), it shows how to use it. When you use svg as source, make sure you reference png later in XAML.

**Comment by dais-set** [comment]
Hi,
It would appear that the video doesn't show anything that's not already in your ReadMe. Anyway, it would also appear the plugin doesn't quite work for production use yet, thanks for the efforts, though!
Best regards,
OR
