### ISSUE TITLE
SVGs in a separate project

### ISSUE THREAD

**Issue by DiagProf** [Redth/ResizetizerNT#28]
Hello Redth,

i have my SVGs in a separate project (see pic). But somehow ResizetizerNT can't handle that. No PNGs are generated in the other projects.
Is there a solution for this?

Best regards
DiagProf
![Solution](https://user-images.githubusercontent.com/56319388/96914030-ba6f9900-14a4-11eb-80a1-10f2cb18c022.png)

[Vehicle.zip](https://github.com/Redth/ResizetizerNT/files/5424922/Vehicle.zip)

**Comment by Redth** [comment]
It can, but your Manufacturer project needs to be directly referenced by your Vehicle.Android, Vehicle.iOS, Vehicle.UWP, etc projects.  Right now you have it referenced by Vehicle only so it is an implicit project reference to the app heads, which Resizetizer can't handle/discover.
