### ISSUE TITLE
Query: Interested in integrated support for Resizetizer in MFractor?

### ISSUE THREAD

**Issue by matthewrdev** [Redth/ResizetizerNT#3]
Hi Redth,

Long time fan, first time caller.

I'm currently adding image IntelliSense, analysis and management support for Resizetizer `SharedImage`s in [MFractor](https://www.mfractor.com/).

Would you be available to join me in a call to discuss what I can do to further help integrate Resizetizer into Visual Studio Mac? For example, an action to `Add Shared Image` from within the right click `Add` menu in the solution pad.

Let me know :)

**Comment by matthewrdev** [comment]
Following up on this, a suggestion for the `BaseSize` attribute.

## Automatic Base Size
When the image asset is a `SharedImage` **and** a bitmap, do not require the `BaseSize` attribute. The `BaseSize` attribute requires that I calculate the correct mdpi resolution, which significantly increases the barrier of entry.

Rather, treat the image as the maximum density version of each platform. Users could then specify a `MaximumSize` and Resizetizer would downsample from there.

When building the [image importer](https://docs.mfractor.com/image-management/image-importer/), I went through several iterations and found that treating an images size as it max density and then downsampling from there was the most intuitive for my users.

**Comment by matthewrdev** [comment]
@Redth Following up on this (again). Here is IntelliSense, tooltips, analysis and image management support added into MFractor for Resizetizer:

**Tooltips**
<img width="653" alt="Screen Shot 2020-03-29 at 8 54 22 am" src="https://user-images.githubusercontent.com/3260473/77835708-14241500-719b-11ea-845a-6805508a19f3.png">

**IntelliSense**
<img width="542" alt="Screen Shot 2020-03-29 at 8 54 28 am" src="https://user-images.githubusercontent.com/3260473/77835709-18e8c900-719b-11ea-8190-db6b00d739b7.png">

**Analysis**
<img width="510" alt="Screen Shot 2020-03-29 at 8 54 37 am" src="https://user-images.githubusercontent.com/3260473/77835710-1a19f600-719b-11ea-92bf-156f62eec095.png">

**Image Management**
<img width="641" alt="Screen Shot 2020-03-29 at 8 55 17 am" src="https://user-images.githubusercontent.com/3260473/77835712-1a19f600-719b-11ea-91a9-829c17f20afe.png">

**Comment by Redth** [comment]
Hey thanks for sharing!

The integration looks nice :). I didn’t expect any tooling to integrate with this, so one thing I’m wondering is if you depend on the output path being the same always (eg: inside obj/resizetizer). 

I agree for the base size suggestion. This problem is hard to solve nicely but I do look your suggestion and will implement that.

**Comment by matthewrdev** [comment]
This solves a significant problem and I'd like to support it :)

To support Resizetizer I am inspecting the `BuildAction` for a project file then including it into my image asset engine. It's all done using the IDE project model and not the obj output.

<img width="1023" alt="Screen Shot 2020-03-29 at 9 59 43 am" src="https://user-images.githubusercontent.com/3260473/77836695-0a52df80-71a4-11ea-931e-047ad273fee3.png">

**Comment by Redth** [comment]
Perfect, this is the right way to discover them!

**Comment by matthewrdev** [comment]
This is all done @Redth, closing this issue.
