### ISSUE TITLE
Generated Images are blank

### ISSUE THREAD

**Issue by waseem852** [Redth/ResizetizerNT#31]
Hi All,
I am using ResizetizerNT 0.2.0 on a Xamarin forms (Android and iOS only) project. When I checked the obj folder, Resizertizer folder is created and the images are just blank. I am using SVG file as the base Image.

![image](https://user-images.githubusercontent.com/6280381/97800861-b6ccd680-1c49-11eb-92b9-54101a102e8f.png)

![image](https://user-images.githubusercontent.com/6280381/97800883-d06e1e00-1c49-11eb-8223-9225edd16c0a.png)

What am I Missing ?

**Comment by Kylar182** [comment]
Same, swapped back to .1 and all normal again

**Comment by waseem852** [comment]
> Same, swapped back to .1 and all normal again

Yes, It is working with 0.1.0. but blank is 0.2.0.

**Comment by Kylar182** [comment]
@waseem852 I'm not an expert but I'd guess the new TintColor Addition is blanking them since I don't have it set on any of my images

**Comment by waseem852** [comment]
> @waseem852 I'm not an expert but I'd guess the new TintColor Addition is blanking them since I don't have it set on any of my images

So the tintcolor is mandatory for this to work on 0.2.0 🤔

**Comment by waseem852** [comment]
Added  TintColor="#FFFFFF" to the <SharedImage/> and result is still the same. Blank.

**Comment by Feroks** [comment]
It seems you need to provide alpha component, so that HEX is 8 digit. Try adding FF at the start of your TintColor value.

**Comment by waseem852** [comment]
> It seems you need to provide alpha component, so that HEX is 8 digit. Try adding FF at the start of your TintColor value.

Hex with 8 digits produce the same results. black blank images. currently only reverting to 0.1.0 works.

**Comment by Feroks** [comment]
Strange. Can you attach one of the images and specify what HEX color you are using?

**Comment by waseem852** [comment]
[Building.zip](https://github.com/Redth/ResizetizerNT/files/5541881/Building.zip)


Image is attached (Zipped because cannot upload SVG). I tried without any tintcolor, tintcolor with #FFFFFF and tintcolor with #FFFFFFFF. All gave blank Black images.

**Comment by Feroks** [comment]
> > Strange. Can you attach one of the images and specify what HEX color you are using?
> 
> [Building.zip](https://github.com/Redth/ResizetizerNT/files/5541881/Building.zip)
> 
> Image is attached (Zipped because cannot upload SVG). I tried without any tintcolor, tintcolor with #FFFFFF and tintcolor with #FFFFFFFF. All gave blank Black images.

@waseem852 This is not a real SVG. It just contains png image as base64 string. I am actually curious how it worked for you on 0.1 version.

**Comment by waseem852** [comment]
> > > Strange. Can you attach one of the images and specify what HEX color you are using?
> > 
> > 
> > [Building.zip](https://github.com/Redth/ResizetizerNT/files/5541881/Building.zip)
> > Image is attached (Zipped because cannot upload SVG). I tried without any tintcolor, tintcolor with #FFFFFF and tintcolor with #FFFFFFFF. All gave blank Black images.
> 
> @waseem852 This is not a real SVG. It just contains png image as base64 string. I am actually curious how it worked for you on 0.1 version.

It was working on 0.1.0 without any issues. I mean the same file.  once upgraded to 0.2.0, it started to generate those black images.

**Comment by Redth** [comment]
In any case, if you're just using a PNG inside a vector, just save it as a PNG and use that instead.  Not sure what would have changed in SkiaSharp between versions but I'm not really sure it's worth trying to support when there's a very reasonable workaround.
