### ISSUE TITLE
What about Xamarin Native?

### ISSUE THREAD

**Issue by roy2k** [Redth/ResizetizerNT#37]
Will be supported on a specific platform?

**Comment by Redth** [comment]
It'll work fine there already.  You can either put your images in a common netstandard2.0 project just like the forms example, or put them in your platform specific projects and set this variable in your project:

```
<PropertyGroup>
    <ResizetizerIncludeSelfProject>True</ResizetizerIncludeSelfProject>
</PropertyGroup>
```
