### ISSUE TITLE
png of svg is a black square.

### ISSUE THREAD

**Issue by AlexGipp** [Redth/ResizetizerNT#39]
This svg: (Zip because svg is not supported)
[viral.zip](https://github.com/Redth/ResizetizerNT/files/5761014/viral.zip)

Gets turned into this png: (Just a black square)
![viral](https://user-images.githubusercontent.com/33844665/103468869-27819380-4d5e-11eb-841f-c4b71d1d67f9.png)

With a different svg it works just fine.
So is there something wrong with my svg, and how do i fix it?

**Comment by bondarenkod** [comment]
I've added an example with your's SVG image 
I've also found a few other SVGs with converting issues. 

![vmware_29_01_2021__17_19_43__982125a6-b087-4683-8642-713d0079687f](https://user-images.githubusercontent.com/3184414/106293021-2f95fb80-6256-11eb-9528-56bd31407274.png)

https://github.com/bondarenkod/ResizetizerNT_issues1

**Comment by AlexGipp** [comment]
Interesting, i wonder what causes that issue.

**Comment by bondarenkod** [comment]
I'll try to debug it later.

**Comment by AlexGipp** [comment]
I could also look into that issue if its not too hard, contrebuiting to this awesome library would be awesome.

**Comment by bondarenkod** [comment]
@AlexGipp 
![explorer_29_01_2021__21_49_41__82956e31-4077-4df5-acb7-87d9fc9fb8ec](https://user-images.githubusercontent.com/3184414/106320779-025c4400-627c-11eb-91e4-6eb0447d6771.png)
using this tool https://github.com/RazrFalcon/svgcleaner (gui in the same repo)
I have two ideas:
- Your file is corrupted.
- Your file has a newer version that not supported by the svgcleaner and skia.sharp

**Comment by bondarenkod** [comment]
I've checked your file using the viewer from the original SVG library 
It is display nothing https://github.com/svg-net/SVG
![SVGViewer_29_01_2021__22_23_24__23bd3890-98bf-4ed8-9993-92e997748d40](https://user-images.githubusercontent.com/3184414/106323808-b19b1a00-6280-11eb-929a-afd43d616b47.png)

**Comment by AlexGipp** [comment]
Those svgs are probably valid though, i just copied the <svg> tag from this website: https://nindo.de/
![Capture](https://user-images.githubusercontent.com/33844665/106340701-051a6180-629b-11eb-8883-9f070d25ab9a.PNG)

**Comment by bondarenkod** [comment]
@AlexGipp I fix your SVG. I hope. 
![image](https://user-images.githubusercontent.com/3184414/106351691-39ffd600-62e6-11eb-959a-f5e152dc4dc9.png)
Once I replaced the `currentColor` with the `orange` the SVGCleaner tool stopped sending me warnings. 
![image](https://user-images.githubusercontent.com/3184414/106351831-551f1580-62e7-11eb-856e-2819ff5b2766.png)
And now I see the image in the app.

**Comment by AlexGipp** [comment]
Interesting thanks for figuring that out!
