### ISSUE TITLE
Generated image  with gradient looks improperly

### ISSUE THREAD

**Issue by yurkinh** [Redth/ResizetizerNT#4]
Hi,
I have tried to use this plugin in one of my test projects and it works perfectly except one thing.
SVG images that have gradients look roughly.
Here is a sample of manually generated image and with your tool.

![compare](https://user-images.githubusercontent.com/17849938/79204687-9e2fd700-7e45-11ea-90ca-40feabf8a7f9.png)
On the left side, we have an image generated with ResizetizerNT.
On the right side manually generated image.
Sizes were generated correctly.
I have attached a sample image
[icon.svg.zip](https://github.com/Redth/ResizetizerNT/files/4474214/icon.svg.zip)

**Comment by Redth** [comment]
@mattleibow do you have any ideas on this one? Surely I'm using SkiaSharp wrong.
