### ISSUE TITLE
Quick question here:  Can someone explain the differences between ResizetizerNT and FFImageLoading.Svg ?

### ISSUE THREAD

**Issue by rs-memosoft** [Redth/ResizetizerNT#58]
I have been trying to use FFImageLoading.Svg and it's been giving me a lot of problems.  I would like to try ResizetizerNT but could someone explain the differences between the two when it comes to the handling of svgs.  Is it the case that behind the scenes they both do the same thing and files are added to the resources of the iOS and Android apps at some point during the build process. 

Would be great if someone could explain the differences for me.  Also from what I understand ResizetizerNT takes the svgs and converts them to pngs.  Am I correct in saying that and also is that the same for FFImageLoading?

**Comment by themronion** [comment]
@rscholey these are two different libraries and they do absolutely different stuff. FF draws your svg-s on the screen in runtime, hence you have the flexibility to change whatever parts and colours of your svg + they are being cached.  While what this library does - it generates png-s from your svg-s for all screen sizes before deploying app to device and in final it is basically the same as if u added regular png resources to your project. Also, there is no image caching as in FF
