### ISSUE TITLE
Xamarin update 

### ISSUE THREAD

**Issue by AlexGipp** [Redth/ResizetizerNT#59]
So i updated the Xamarin.Forms nuget from `5.0.0.1931` to `5.0.0.2012`  which resulted in a bunch of svgs not loading correctly anymore (Just shows nothing). Do you guys know why that happens and if i can do anything to fix that?

Repo: https://github.com/AlexGipp/Nindo.Mobile/tree/feature/Viral
(Afte downgrading the nuget to  `5.0.0.1931` it worked again)

**Comment by onlyargon** [comment]
Same issue here. After update to the Xamarin forms ```5.0.0.2012``` png files are not loading 😭

**Comment by themronion** [comment]
@onlyargon @AlexGipp rename your files

**Comment by AlexGipp** [comment]
@themronion thanks for the suggestion but how and why would that solve the problem, and why does it still work with the old version?

**Comment by themronion** [comment]
Just try it. It will solve your problem

**Comment by bmacombe** [comment]
See #44

**Comment by onlyargon** [comment]
> @onlyargon @AlexGipp rename your files so that they match the android resources naming conventions. So for example if u have a file someFile.svg rename it to some_file.svg

This is working. Thanks.

**Comment by AlexGipp** [comment]
Thanks for your help, I will check if that solves my problem 👍

**Comment by AlexGipp** [comment]
Hey, after renaming the files to match the Android standard I get the error: `One or more errors occurred.` I already tried to clean/rebuild the Solution. Does anyone know why that happens and what the actual problem is?

**Comment by themronion** [comment]
@AlexGipp it is a known issue also: https://github.com/Redth/ResizetizerNT/issues/35
