### ISSUE TITLE
ResizetizerNT not working to load SVG images in Xamarin Forms version 5.0.0.2012

### ISSUE THREAD

**Issue by SrilaxmiPalle** [Redth/ResizetizerNT#62]
Hi,

Using ResizetizerNT package we are unable to load SVG images in Xamarin forms latest stable version 5.0.0.2012, it is working fine till version 5.0.0.1931. 
 
Because of which we are unable to use it, can you people suggest any solution ASAP.

**Comment by dgerding** [comment]
I think I'm having the same problem. I've tried the trick of renaming the svg files, also tried removing and re-adding as SharedImage build property. No luck. The png-s aren't being made anymore.

**Comment by paradisehuman** [comment]
I have the same issue as you.

**Comment by dilipgandham** [comment]
I am also facing the same issue.

**Comment by themronion** [comment]
https://github.com/Redth/ResizetizerNT/issues/59

**Comment by SrilaxmiPalle** [comment]
Solution provided in issue #59 is working, Thank you.

**Comment by SrilaxmiPalle** [comment]
After I renamed my files and rebuilt my solution I got the error: One or more errors occurred. every time I started to run my app.
Can you please suggest the solution for it.

**Comment by themronion** [comment]
@SrilaxmiPalle restart visual studio. Please close it again
