### ISSUE TITLE
Deployment error with 0.3.0

### ISSUE THREAD

**Issue by TheObliterator** [Redth/ResizetizerNT#82]
I get a build/deployment error in my Android/iOS projects when upgrading to v0.3.0 of the plugin (v0.2.0 works fine).

Error: Resizetizer.NT.targets(305,3): error : Value cannot be null.
It complains about the 'source' parameter being null.

The problem occurs even if I don't have images marked as SharedImage/ResizetizerNt build action.
Happy to supply additional logs if you point me in the right direction.

**Comment by r2d2rigo** [comment]
I'm experiencing this too - the library seems to fail to build when there are no `SharedImage` assets in any of the projects.

**Comment by TheObliterator** [comment]
@r2d2rigo That makes sense, I'd used the property editor in VS to set the base size for the images - this had updated the project entries from 'SharedImage' to 'ResizetizerNt' build action. Your null fix should resolve that nicely, but I simply manually set the build action back to 'SharedImage' which also resolved my issue.
